import AuthLinks from '@/ui/auth-link';

import './style.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
};

export default function AuthLayout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <AuthLinks />
      {children}
    </div>
  );
}
