import Footer from '@/ui/footer';
import Header from '@/ui/header';
import { Metadata } from 'next';
import { ErrorWrapper } from './error-wrapper';

export const metadata: Metadata = {
  title: {
    default: 'NextJS15 mastery',
    template: '%s | NextJS15',
    absolute: ''
  },
  description: 'Generated by Next.js'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <ErrorWrapper>{children}</ErrorWrapper>
        <Footer />
      </body>
    </html>
  );
}
